### ISSUE TITLE
The linker command, for windows, is exceeding the maximum character length

### ISSUE THREAD

**Issue by rockcavera** [nim-lang/csources_v2#1]
I don't know if it's the final version, but if it is, it will be necessary to correct the names of the C files generated for windows. At the moment the command that calls the linker has almost 9000 characters, which exceeds the [Windows limit of 8191](https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation). This is due to the stdlib file names being like this: `@m..@s..@s.choosenim@stoolchains@snim-@hdevel[...]`

For the other destinations the names are also like this.

**Comment by ringabout** [comment]
Hello, it is not a final version and will be used for the devel version only https://github.com/nim-lang/Nim/pull/21108.

**Comment by ringabout** [comment]
Now it should be better https://github.com/nim-lang/csources_v2/tree/master/c_code/2_5

**Comment by rockcavera** [comment]
Now the line is 6387 characters long. Of course, it's not a problem with the scripts that generate csource, but rather with how the Nim compiler names the compiled files.
